Update control
Add python3-requests. When trying to add a repository by terminal it returns this:

sudo apt add-repository ppa:i2p-maintainers/i2p
[sudo] contraseña para federico:         
Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintSources/mintSources.py", line 11, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

Se verifica que version de python es:
code /usr/lib/linuxmint/mintSources/mintSources.py
The first line says #! /usr/bin/python3

Missing package is installed: apt install python3-requests.
Repository: "apt add-repository ppa: i2p-maintainers/i2p" is added.